
import { MenuBar } from "menu.slint";
import { MainContentList, WorkspaceItem } from "listbox.slint";

import { Button } from "std-widgets.slint";

MainWindow := Window {

    callback set_workspace_path();
    callback ros_workspace_build(string);
    callback ros_workspace_sourced(string);

    property <[WorkspaceItem]> workspace_list: [
        { name: "fod4wind", path: "/workspace/fod4wind_ws", nodes: 5, ros_version: "foxy"},
        { name: "genius", path: "/workspace/genius_Ws", nodes: 8, ros_version: "noetic"},
        { name: "healthdrone", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "genius", path: "/workspace/genius_ws", nodes: 4, ros_version: "noetic"},
        { name: "healthdrone", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "healthdrone", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "healthdrone", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "healthdrone", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "test2", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "genius", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
        { name: "end", path: "/workspace/healthdrone_ws", nodes: 4, ros_version: "noetic"},
    ];

    title: "ROS Manager";
    default-font-family: "Noto Sans";
    HorizontalLayout {
        padding: 0; spacing: 0;
        menu := MenuBar { 
            set_path_clicked => { root.set_workspace_path(); }
        }
        MainContentList {
            request_ros_workspace_build(path) => { root.ros_workspace_build(path); } 
            request_ros_workspace_sourced(path) => { root.ros_workspace_sourced(path); }
            
            workspace-list: root.workspace_list;
            // item_height => 50px;
        }
    }
}

