import { Button, VerticalBox, ListView, HorizontalBox } from "std-widgets.slint";
import { Skin } from "skin.slint";

export MainContentList := GridLayout {
    callback request-ros-workspace-sourced();
    callback request-ros-workspace-build();    

    // list box that goes col 1-2-3
    ListView {
        row: 1;
        col: 1;
        colspan: 3;
        width: 650px;
        height: 350px;
        border-width: 0;
        background: Skin.palette.mainContentList;
        for data in [
            { folderName: "fod4wind", folderPath: "/workspace/fod4wind_ws", NodeNum: 5},
            { folderName: "genius", folderPath: "/workspace/genius_ws", NodeNum: 8},
            { folderName: "healthdrone", folderPath: "/workspace/hd_ws", NodeNum: 4},
        ] : HorizontalBox {
            height: 50px;
            width: (parent.width) - 20px;
            HorizontalBox { 
                alignment: space-between;                
            fName := Text {
                text: data.folderName;
                color: #fff;
                vertical-alignment: center;
                font-size: Skin.MediumFont;
            }
            fPath := Text {
                text: data.folderPath;
                color: #fff;
                vertical-alignment: center;
                horizontal-alignment: left;
                font-size: Skin.MediumFont;
            }
            wsNodeNum := Text {
                text: "Nodes: " + data.NodeNum;
                color: #fff;
                vertical-alignment: center;
                horizontal-alignment: left;
                font-size: Skin.MediumFont;
            }
        }
            Button { 
                text: "source";
                width: 75pt;
                ma := TouchArea {}
                background: ma.has-hover ? rgba(100%, 100%, 100%, 50%) : Skin.palette.button;

                clicked => {request-ros-workspace-sourced();}
            }
            Button {
                text: "build";
                width: 75pt;
                ma2 := TouchArea {}
                background: ma2.has-hover ? rgba(100%, 100%, 100%, 50%) : Skin.palette.button;
                clicked => { request-ros-workspace-build(); }
            }
        }
    }
}   


// Text {
//     text: "Source";
//     color: #fff;
//     horizontal-alignment: TextHorizontalAlignment.center;
//     vertical-alignment: TextVerticalAlignment.center;
//     font-size: Skin.MediumFont;
//     font-family: "Noto Sans";
// }