struct Palette := {
    menuBar : brush,
    mainContentList : brush,
    text : brush,
    highlight : brush,
    button: brush,
}

global Skin := {
    property<Palette> palette : {
       menuBar : #2f3136,
       mainContentList :  #36393f,
       text : #dcddde,
       highlight : #4f545c,
       button : #dcddde,
    };

    // From Skin::initHints in Skin.cpp
    property <length> DefaultFont: 12px;
    property <length> TinyFont: 9px;
    property <length> SmallFont: 10px;
    property <length> MediumFont: 13px;
    property <length> LargeFont: 20px;
    property <length> HugeFont: 27px; // (also, bold)
    property <length> TitleFont: 10px; // (also, bold)
}

//    --scrollbar-thin-thumb: #202225;
// --scrollbar-thin-track: transparent;
// --background-primary: #36393f;
// --background-secondary: #2f3136;
// --background-secondary-alt: #292b2f;
// --background-tertiary: #202225;
// --background-accent: #4f545c